services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capstone_service
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src # Bind mount the source directory
      - ./package.json:/app/package.json # Ensure package.json is always up to date
      - ./tsconfig.json:/app/tsconfig.json # Bind mount tsconfig for TypeScript
      - central_node_modules:/app/node_modules # Use a named volume for node_modules
    # command: ['npm', 'run', 'start:dev']
    deploy:
      resources:
        limits:
          memory: 4G # Set memory limit

volumes:
  central_node_modules: