version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: social_app_redis_service
    restart: always
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capstone_service
    depends_on:
      - redis
    restart: always
    env_file:
      - .env.local
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
